### ISSUE TITLE
Организация проекта

### ISSUE THREAD

**Issue by dywork** [Ganzhurova/FSD#1]
Дарима, привет!) Давай знакомиться, меня зовут, Саша. Я буду проводить твое первое ревью и если что, по любым вопросам можешь писать мне в тг: @dywork :)

В целом проекты хорошо написаны, молодец 👍

**Comment by dywork** [comment]
Я предлагаю в папке theme оставить **variables.scss** и можно **fonts.scss**, а вот **global.scss** и **mixins.scss** вытащить куда ни будь по типу styles/ т.к. они не только к теме относятся, но и ко всему проекту.

**Comment by Ganzhurova** [comment]
Файлы global.scss и mixins.scss перемещены в папку styles

**Comment by dywork** [comment]
Все подключаемые библиотеки должны быть максимально абстрагированы от реализации проекта. Т.е. они должны использоваться 'под капотом', но при этом не сильно влиять на код.
Т.е. если либы требуют подключения своих скриптов/стилей непосредственно - то для этого должна быть отдельная папка(для всех используемых либ), где будут лежат стили и скрипты этих либ.
А твои компоненты должны быть реализованы твоей архитектурой, но просто с использованием файлов либы.

т.е., например ты хочешь подключить calendar. Создаешь libs/Сalendar в index.js ты пишешь класс Calendar где описываешь инициализацию этого календаря (подключение air-datepicker), calendar.scss - переопределяшь стили и т д. А в компоненте components/Calendar ты подключаешь свою библиотеку. Нужно это что бы код твоего компонента не зависел от используемой библиотеки, и ты, в идеале, могла бы подключить другую библиотеку не меняя код самого компонента.
