### ISSUE TITLE
Pug

### ISSUE THREAD

**Issue by dywork** [Ganzhurova/FSD#3]
**Ссылки**. У нас в стандартах есть [требование](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.11) не использовать ссылки заглушки (href="#"). И для внешних ссылок нужно добавить атрибуты из пунктов [2.13](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.13) и [2.14](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.14). Ссылки на соц. сети например являются внешними. И я бы ещё ссылкам-иконкам добавил атрибут **title** для пояснения куда ведут)

**Comment by dywork** [comment]
![image](https://user-images.githubusercontent.com/17548109/176114203-95cc82a4-6f67-420d-9be2-18c1158bb0e0.png)

![image](https://user-images.githubusercontent.com/17548109/177077950-aa9d9bff-d78d-4528-9611-fdb3e5324759.png)

используй code spell checker

**Comment by dywork** [comment]
лишние классы? 

![image](https://user-images.githubusercontent.com/17548109/177075888-71b09905-3d3c-418d-8807-b0ba9545d38a.png)

**Comment by dywork** [comment]
# button

- а для чего нам `inner` этот?

  ![image](https://user-images.githubusercontent.com/17548109/177078809-428949c5-f71d-41fa-9109-138e954aa2e1.png)

- сейчас модификаторы кнопки объединяют в себе много свойств, которые я бы перенес в свойства по умолчанию, например размеры и цвет заливки самые чаще повторяющиеся, т.е. у нас в deafultе классе .button заданы самые чаще повторяющиеся размеры и цвет заливки, а другие варианты задаем через уже кастомные модификаторы. **Например:** сейчас `button--with-arrow` отвечает и за заливку и за размеры и за наличие того самого arrow в названии, лучше если модификатор `--with-arrow` будет отвечать именно за наличие стрелки, а размер или заливку определяют либо свойства по умолчанию либо другие модификаторы.

**Comment by OlgaMaurer** [comment]
в [best-practices](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.1) описаны правила именования модификаторов. Ты использовала допустимый в БЭМ стиль, но пожалуйста исправь написание всех модификаторов через одно нижнее подчеркивание(_)
